name: CI

on: [push, pull_request]

permissions:
  contents: read
  packages: write

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: reportengine
          POSTGRES_USER: user
          POSTGRES_PASSWORD: pass
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U user -d reportengine"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Install root deps
        run: npm ci
      - name: Install backend deps
        run: |
          cd packages/backend
          npm ci
      - name: Wait for Postgres
        run: |
          until pg_isready -h 127.0.0.1 -p 5432 -U user -d reportengine; do sleep 1; done
      - name: Run migrations
        env:
          DATABASE_URL: postgresql://user:pass@127.0.0.1:5432/reportengine
        run: |
          psql "$DATABASE_URL" -f packages/backend/migrations/001_add_indexes_and_mv.sql || true
      - name: Run backend tests
        env:
          DATABASE_URL: postgresql://user:pass@127.0.0.1:5432/reportengine
          NODE_ENV: test
        run: |
          cd packages/backend
          npm test --silent

      - name: Install frontend deps
        run: |
          cd packages/frontend
          npm ci

      - name: Run frontend tests
        env:
          CI: true
        run: |
          cd packages/frontend
          npm test --silent

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v4
        with:
          context: ./packages/backend
          file: ./packages/backend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/reportengine-backend:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/reportengine-backend:latest

      - name: Build and push frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./packages/frontend
          file: ./packages/frontend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/reportengine-frontend:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/reportengine-frontend:latest
